# docker/docker-compose.yml
# version: '3.8' - REMOVIDO (obsoleto no Docker Compose v2+)

# Configuração global para desabilitar BuildKit
x-build-config: &build-config
  network: host
  
services:
  mongo:
    image: mongo:8.0
    container_name: ecommerce-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 123456

  redis:
    image: redis:7.4-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  rabbitmq:
    image: rabbitmq:4-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  catalog-api:
    image: catalog-api
    container_name: catalog-api
    build:
      context: .
      dockerfile: src/Services/Catalog/Catalog.API/Dockerfile
      <<: *build-config
    ports:
      - "6001:8080" 
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__MongoDbConnection=mongodb://admin:123456@mongo:27017
    depends_on:
      - mongo

  identity-api:
    image: identity-api
    container_name: identity-api
    build:
      context: .
      dockerfile: src/Services/Identity/Identity.API/Dockerfile
      <<: *build-config
    ports:
      - "5001:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__MongoDbConnection=mongodb://admin:123456@mongo:27017

  basket-api:
    image: basket-api
    container_name: basket-api
    build:
      context: .
      dockerfile: src/Services/Basket/Basket.API/Dockerfile
      <<: *build-config
    ports:
      - "7001:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Redis=redis:6379
    depends_on:
      - redis
      - rabbitmq

  order-api:
    image: order-api
    container_name: order-api
    build:
      context: .
      dockerfile: src/Services/Order/Order.API/Dockerfile
      <<: *build-config
    ports:
      - "8001:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__MongoDbConnection=mongodb://admin:123456@mongo:27017
    depends_on:
      - mongo
      - rabbitmq

  api-gateway:
    image: api-gateway
    container_name: api-gateway
    build:
      context: .
      dockerfile: src/Gateway/ApiGateway/Dockerfile
      <<: *build-config
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    depends_on:
      - identity-api
      - catalog-api
      - basket-api
      - order-api

  payment-api:
    image: payment-api
    container_name: payment-api
    build:
      context: .
      dockerfile: src/Services/Payment/Payment.API/Dockerfile
    ports:
      - "5006:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - rabbitmq
      - seq
  
  notification-api:
    image: notification-api
    container_name: notification-api
    build:
      context: .
      dockerfile: src/Services/Notification/Notification.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - rabbitmq
      - seq

  healthchecks-ui:
   image: xabarilcoding/healthchecksui:latest
   container_name: healthchecks-ui
   ports:
    - "5005:80" # acesso no navegador pela porta 5005
   environment:
      - HealthChecksUI__HealthChecks__0__Name=Identity API
      - HealthChecksUI__HealthChecks__0__Uri=http://identity-api:8080/health
      - HealthChecksUI__HealthChecks__1__Name=Catalog API
      - HealthChecksUI__HealthChecks__1__Uri=http://catalog-api:8080/health
      
      - HealthChecksUI__HealthChecks__2__Name=Basket API
      - HealthChecksUI__HealthChecks__2__Uri=http://basket-api:8080/health
      
      - HealthChecksUI__HealthChecks__3__Name=Order API
      - HealthChecksUI__HealthChecks__3__Uri=http://order-api:8080/health
      
      - HealthChecksUI__HealthChecks__4__Name=API Gateway
      - HealthChecksUI__HealthChecks__4__Uri=http://api-gateway:8080/health
      
      - HealthChecksUI__HealthChecks__5__Name=Payment API
      - HealthChecksUI__HealthChecks__5__Uri=http://payment-api:8080/health

      - HealthChecksUI__HealthChecks__6__Name=Notification API
      - HealthChecksUI__HealthChecks__6__Uri=http://notification-api:8080/health

      # Configurações de tempo (Atualiza a cada 10 segundos)
      - HealthChecksUI__EvaluationTimeInSeconds=10
      - HealthChecksUI__MinimumSecondsBetweenFailureNotifications=60
   depends_on:
      - identity-api
      - catalog-api
      - basket-api
      - order-api
      - api-gateway


  seq:
    image: datalust/seq:2024
    ports:
      - "5341:80"
    environment:
      ACCEPT_EULA: Y

      

volumes:
  mongo_data:
  redis_data:

  


